services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    