services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    env_file:
      -  config/.env.backend
      -  config/.env.pg
      - ./config/.env.redis
    networks:
      - my_network
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      -  config/.env.pg
    networks:
      - my_network
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    container_name: redis_db
    restart: always
    env_file:
      - ./config/.env.redis
    networks:
      - my_network
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

networks:
  my_network:
    driver: bridge

volumes:
  pg_data:
  redis_data:
