services:
  frontend:
    image: 10.0.10.12:5000/frontend:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - config/.env.backend
      - config/.env.pg
      - config/.env.redis
    networks:
      - my_network
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    restart: always
    env_file:
      - config/.env.pg
    networks:
      - my_network

  redis:
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_ARGS: "--requirepass mypassword"
    networks:
      - my_network
    ports:
      - 6379:6379
      - 8001:8001

networks:
  my_network:
    driver: overlay

