name: Тестирование и пробная развертка приложения

on:
  push:
    branches:
      -  develop
    
jobs:
  build:
    runs-on: [ self-hosted, staging ]
    steps:
      - name: Синхронизация проекта с репозиторием
        uses: actions/checkout@v4
          
  test:
    needs: build
    runs-on: [ self-hosted, staging ]
    steps:
      - name: Тут будут тесты
        run: sleep 10
  
  stage:
    needs: test
    runs-on: [ self-hosted, staging ]
    steps:
      - name: Тестовый запуск проекта
        run: |
          COMPOSE_PROJECT_NAME=${{ github.ref_name }} \
          docker compose -f ${{ github.workspace }}/compose.yml up -d --build --force-recreate