name: Lint

on:
  push:
    branches: [ 'feature/**' ]
  pull_request:
    branches: [ 'develop' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3
        with:
            src: ./backend
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: docker compose up -d --build --force-recreate

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
