name: Lint

on:
  push:
    branches: [ 'feature/**' ]
  pull_request:
    branches: [ 'feature/**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3
        with:
            src: ./backend
        continue-on-error: true

      - uses: actions/setup-node@v4

      - run: |
          npm install -g htmlhint stylelint eslint
          npm install --save-dev @typescript-eslint/parser @typescript-eslint/eslint-plugin

      - run: htmlhint "./frontend/**/*.html"
        continue-on-error: true

      - run: npx stylelint "./frontend/**/*.{css,scss}" --color
        continue-on-error: true

      - run: npx eslint "./frontend/**/*.ts" --color
        continue-on-error: true